sstsimulator/sst-sqe

buildsys/bamboo.sh
Don't attempt the clone a second time when running the Make Dist test
Adjust the path to bamboo for the second invocation.
Omit execution of the iris and portals tests since their element subdirectories are gone.
=> Catching up bamboo with other changes

test/testSuites/testSuite_check_maxrss.sh
Verbose output varies depending on whether more than one thread is requested.
=> Modify test to accomodate output

test/include/testDefinitions.sh
In stead of requiring from a specified list, accept any positive integer.
For tests that use a python wrapped invocation line, Ember Sweep is covered here, Scheduler test6 has been covered in the test Suite and MacSim is not provided for.  (Oct 2015, of those only Ember Sweep passes, for n>1.)
=> Generalize the Multi Thread Patch Routine

test/testSuites/testSuite_BadPort.sh
When the test depends on a segfault, you cannot depend on stdout being
properly flushed.  Prepend call to ${sut} with 'stdbuf -o0 -e0' to turn
off stdout and stderr file buffering.
=> BadPort: Remove stdout buffering.

buildsys/bamboo.sh
It enters an infinite loop that time-limit processing doesn't terminate.
=> Don't Run Scheduler Test 6 on MacOS for now

buildsys/bamboo.sh
Re-enable Scheduler test 6 on MacOS
=> This reverts commit a962ad1828b90acbd53e1ac464fca1a7e72c55d7.

test/testSuites/testSuite_BadPort.sh
Faulty test invocation resulted in a Pass without executing the test.
=> Enhance BadPort test output

test/testSuites/testSuite_scheduler_DetailedNetwork.sh
Scheduler is reported to be known to be not thread-safe
=> Omit scheduler test 6 also if n>1

buildsys/bamboo.sh
Load modulefile for OpenMPI 1.6.5 (bundled with Ubuntu 16.04).  Also change loading of GLPK to load default version (version bundled with Ubuntu 16.04B) instead of explicit version 4.54.
=> Add support to build on Ubuntu 16.04

buildsys/bamboo.sh
Add support for bundled OpenMPI 10.10 on Sandie COE RHEL 7
=> Adjust bamboo.sh for OpenMPI 1.10 on COE RHEL 7

buildsys/bamboo.sh
Ubuntu 16.04 is still pre-release and changing.   Jon filed a bug report with Ubuntu about the need for this kludge.   So things may change
=> Add Ubuntu 16.06 specific module init code.

test/testSuites/testSuite_Ariel.sh
This worked in December when the code was originally created and would work again in April when the day of the year was 100 or greater.
=> fix octal/decimal issue

test/testSuites/testSuite_Ariel.sh
Ariel test is conditional on finding Pin Library.
Pin installed on Ubuntu VM, but, for yet to be determined reason, Ariel still does not work.
=> Temporary Skip Ariel on Ubuntu

test/testInputFiles/testSdlFiles/HybridSim/sdl3-2-edit.py
String params must not have empty strings, causes exception in core
with new param code.
=> Fix HybridSim for empty string params - Causing core exception

test/testSuites/testSuite_memHSieve.sh
This reverts commit 2c85bb6a205795723a94b36074d1cd13ee4403fd.
=> Revert "Skip memHS test if Ariel dot-h file is not found"

buildsys/bamboo.sh, buildsys/deps/bin/sstDep_qsim_0.2.1.sh
Enable Qsim and in preparation for release, use the patch from element/qsimComponent, rather than SQE
=> Qsim patch elements

test/testSuites/testSuite_sst_mcopteron.sh
As Issue 129 said on February 22, omit McOperon test2
=> Per Issue 129, omit mit McOpreron test2

buildsys/bamboo.sh
Changed the init code for Linux platforms to try 1 of 2 different methods to initialize the module utility.  Afterwards, it tries to perform a module avail via the ModuleEx wrapper.  This should fix the issue with Ubuntu 14.04 failing Since the new Jenkins upgrade.
=> improve module utility init code

test/testSuites/testSuite_embernightly.sh
This test clean-up code code doesn't work on MacOS.  Don't complain about the test failure for pages and pages.
=> Reduce warning from MacOS 

test/utilities/moduleex.sh
change moduleex.sh to check to see if 'module' command is available, and print error and return error code if module command is not working.  To address issue #7
=> Fix moduleex for issue #7

test/include/testSubroutines.sh
Verify that the Valgrind error is from the expected openmpi error, before simply ignoring one error.
=> Better mpi chk

test/testSuites/testSuite_CramSim.sh
"exit" command in test Suite results in silent failure.
=> Remove "exit" from test Suite

test/testSuites/testSuite_partitioner.sh
This flag was inserted (long ago) in response to core issue 21.
Verification that it was not longer need occurred on January 4th.  This removes it from the test Suite in SQE
=> Update testSuite_partitioner.sh removing "--run-mode init"

test/testSuites/testSuite_partitioner.sh
Partitioner test is Multi-Rank.
It is known that Multi-Thread and Multi-Rank do not work together.
See Elements issue 228
=> Omit partitioner Suite on Multi-Thread

buildsys/bamboo.sh, test/testSuites/testSuite_Ariel.sh, test/testSuites/testSuite_EmberSweep.sh, test/testSuites/testSuite_SiriusZodiacTrace.sh, test/testSuites/testSuite_cacheTracer.sh, test/testSuites/testSuite_cassini_prefetch.sh, test/testSuites/testSuite_embernightly.sh, test/testSuites/testSuite_memHA.sh, test/testSuites/testSuite_memHSieve.sh, test/testSuites/testSuite_memHierarchy_sdl.sh, test/testSuites/testSuite_partitioner.sh, test/testSuites/testSuite_prospero.sh, test/testSuites/testSuite_simpleComponent.sh, test/testSuites/testSuite_simpleLookupTableComponent.sh, test/testSuites/testSuite_simpleMessageGeneratorComponent.sh, test/testSuites/testSuite_zoltan.sh, test/utilities/timeLimitEnforcer.sh
The main change distributed among many test Suites is to move all writes to elements for the testing to the (SQE) test sub-tree.
Testing on the Any Branch tester inspired resolving the conflict between out-of-source build and the make-dist test.
Finally an option (environment variable) was introduced in bamboo.sh (dotests) to verify that the move is complete, to remove write permission from the elements sub-tree before running the tests.
=> No Write to Elements subtree by SQE test

buildsys/bamboo.sh
Initialize the environment variable NUMA_PARAM to a blank.
Only define a value if rank count is defined and greater than 1.
=> Refine definition of map-by

buildsys/bamboo.sh, test/testSuites/testSuite_Messier.sh, test/testSuites/testSuite_Samba.sh, test/testSuites/testSuite_SiriusZodiacTrace.sh, test/testSuites/testSuite_cacheTracer.sh, test/testSuites/testSuite_memHA.sh, test/testSuites/testSuite_memHierarchy_sdl.sh, test/testSuites/testSuite_merlin.sh, test/testSuites/testSuite_partitioner.sh, test/testSuites/testSuite_simpleComponent.sh, test/testSuites/testSuite_simpleLookupTableComponent.sh, test/testSuites/testSuite_simpleSimulation_CarWash.sh
This adds the map-by numa to 12 tests where it was previously over-looked
It also provides a third attempt at under what conditions to actually make the insertion.
The latter, inadvertently, skips the insertion on the zoltan and partitioner tests which were failing in the overnight on Yosemite and El Capitan Xcode8.
=> Get the rest

buildsys/bamboo.sh
Change bamboo to use clone  option "--depth 1", unless over ridden by environment variable, SST_GIT_CLONE_DEPTH_PARAMETER.
This is for sst-elements, sst-core and MACRO.   (Bamboo does not control the sqe down-load (clone).
=> Clone by depth

test/utilities/timeLimitEnforcer.sh
This change does not fix El Captain time limit processing, but eliminates some cases on Linux where the wrong sst is killed.    (It preserves current Darwin processing.)
=> Remove e from ps -ef on Linux

test/utilities/timeLimitEnforcer.sh
Strengthen the Time Limit processing on MacOS by taking advantage of the Mac program pstree to find the tasks that need to be killed.
=> Use pstree

buildsys/bamboo.sh
The memH with Ariel Sweep Project is split into two parts run on alternate nights.    The recent enhancements to memHierarchy increased the run times for the Project such that one of the parts was taking 7 to 8 hours.   This moves one test Suite between parts to better balance the tests.   It may be necessary to further partition the tests.
=> ReBalance the memH Sweep tests

test/include/testDefinitions.sh
Remove the feature of bamboo multi-rank processing that inserts a mpirun call even single rank is specified.
=> Fix/tweak bamboo Multi processing

buildsys/bamboo.sh
This change will allow us to used any Boost or MPI version even if it is not the default.  Also added support for No Boost to be loaded.
=> Add Support for any Boost and MPI versions 

test/testSuites/testSuite_SiriusZodiacTrace.sh
Remove multi-rank specific code from sirius Zodiac testSuite.  It was previously required.  Now it's not acceptable.
=> Simple, uncomfortable fix for SZT multi-rank

test/testSuites/testSuite_juno.sh
The PMIX bug has been fixed with the update to $TEMP. It should be safe to revert this change.
=> Reverting PMIX ignore -- fixed on system

buildsys/bamboo.sh
Fixing core config options for macro tests.  Macro was using the incorrect macrobaseoptions when it should have been using corebaseoptions when building the core.
=> Fix to allow Macro to run Py3 with SST-Core

test/testSuites/testSuite_memHSieve.sh
Ensure test only runs if Pin is present, even if the Ariel library has been built.
=> Match run criteria for memHSieve suite to that of the Ariel suite

buildsys/bamboo.sh, buildsys/deps/bin/sstDep_dramsim3_stabledevel.sh, buildsys/deps/bin/sstDependencies.sh
NOTE: Any build system must have CMake V3+ loaded.  IF CMake V3+ is not available, the env variable `export SST_WITHOUT_DRAMSIM3=1` must be set
=> Adding build and configuration changes to support DRAMsim3

buildsys/bamboo.sh
The update to 13.4 causes this to trigger a failure, but it doesn't even do anything anymore.
=> Remove unused macOS version dispatch

buildsys/bamboo.sh
Follow-up of #1125 that fixes a misunderstanding of `if [[ ${SST_STOP_AFTER_BUILD:+isSet} == isSet ]] ; then`.
=> Build exit code part 2

buildsys/bamboo.sh
=> Fix tests when elements are intentionally not built

buildsys/bamboo.sh, buildsys/deps/bin/sstDep_dramsim3_stabledevel.sh, test/testSuites/testSuite_macro.sh
Callers should set `export MAKEFLAGS="-j4"` or `export MAKEFLAGS="-j$(nproc)"` instead.
Cannot be merged until the Jenkins jobs add this.
=> remove explicit parallelism in make calls
