sstsimulator/sst-sqe

- buildsys/bamboo.sh
- test/testSuites/SuitesToOmitFromAll
Primarily make the Bamboo project all attempt to be more inclusive, but provide clearer exclusions of what is not included particularly those that depend on gem5.
> Enhance project all

- buildsys/bamboo.sh
Done by adding a bash subroutine that would also work for the existing 4 Yosemite Clang configuration.
> Add clang-700.1.76 to bamboo

- buildsys/bamboo.sh
> Add El Capitan to bamboo.sh

- test/testSuites/testSuite_partitioner.sh
Adapt the partitioning test Suite to better match multi-thread
> Excess inst

- test/testSuites/testSuite_partitioner.sh
Collect testing changes for multi-thread test
> Partitioner work

- test/testReferenceFiles/test_cassini_prefetch_nbp.out
- test/testReferenceFiles/test_cassini_prefetch_nopf.out
- test/testReferenceFiles/test_cassini_prefetch_sp.out
- test/testReferenceFiles/test_memHierarchy_sdl2_1.out
- test/testReferenceFiles/test_memHierarchy_sdl3_1.out
- test/testReferenceFiles/test_memHierarchy_sdl3_2.out
- test/testReferenceFiles/test_memHierarchy_sdl3_3.out
- test/testReferenceFiles/test_memHierarchy_sdl4_1.out
- test/testReferenceFiles/test_memHierarchy_sdl4_2.out
- test/testReferenceFiles/test_memHierarchy_sdl5_1.out
- test/testReferenceFiles/test_memHierarchy_sdl8_1.out
- test/testReferenceFiles/test_memHierarchy_sdl8_3.out
- test/testReferenceFiles/test_memHierarchy_sdl8_4.out
- test/testReferenceFiles/test_memHierarchy_sdl9_1.out
- test/testReferenceFiles/test_memHierarchy_sdl9_2.out
- test/testReferenceFiles/test_memHierarchy_sdl_1.out
- test/testReferenceFiles/test_memHierarchy_sdl_2.out
- test/testReferenceFiles/test_memHierarchy_sdl_3.out
- test/testReferenceFiles/test_miranda_copybench.out
- test/testReferenceFiles/test_miranda_inorderstream.out
- test/testReferenceFiles/test_miranda_randomgen.out
- test/testReferenceFiles/test_miranda_revsinglestream.out
- test/testReferenceFiles/test_miranda_singlestream.out
- test/testReferenceFiles/test_miranda_stencil3dbench.out
- test/testReferenceFiles/test_miranda_streambench.out
New Reference files for Cassini Prefetch, memH sdl, and Miranda in response to Ariel updates.
> New ref4 ariel

- buildsys/bamboo.sh
Remove McNiagara test invocation per Issue # 138
> Remove invocation of McNiagara test from bamboo.sh

- test/include/testDefinitions.sh
- test/testSuites/testSuite_EmberSweep.sh
Move Multi-thread selection for EmberSweep to the test Suite.
> Move mt4 es

- buildsys/bamboo.sh
The new configure is derived from sstmainline_config_memH_wo_openMP
> Create a new configuration in bamboo specifically for deveautotest

- buildsys/bamboo.sh
- buildsys/bamboo_macro.sh
- test/utilities/TimeoutEx.sh
Adding timeout feature for when we perform the git clones
> Timeout for git clones

- buildsys/bamboo.sh
- test/utilities/TimeoutEx.sh
Should fail testing if fails to build docs.  Also added comment to TimeoutEx.
> Changes to build documentation on split core

- buildsys/bamboo.sh
This is round two of Make Dist changes
Ariel, etc are still not fixed
> Merge in the basic make-dist changes.

- test/testInputFiles/EmberSweepGenerator.py
- test/testSuites/testSuite_EmberSweep.sh
> Add test number to test name in sweep

- test/testSuites/testSuite_qsimComponent.sh
> Adjust to split core paths

- buildsys/deps/bin/sstDependencies.sh
> Try Again with Qsim

- test/testSuites/testSuite_Ariel.sh
- test/testSuites/testSuite_EmberSweep.sh
- test/testSuites/testSuite_partitioner.sh
- test/testSuites/testSuite_prospero.sh
- test/testSuites/testSuite_qsimComponent.sh
- test/testSuites/testSuite_scheduler_DetailedNetwork.sh
- test/testSuites/testSuite_zoltan.sh
- test/utilities/timeLimitEnforcer.sh
Did not include Suites, EmberSweep and scheduler_DetailedNetwork.  The 7 lines that are in all other Suites need modification for the Python wrapping of the SST invocation.
> Include Time Limit reporting code in previously omitted Suites

- test/testReferenceFiles/test_cassini_prefetch_nbp.out
- test/testReferenceFiles/test_cassini_prefetch_sp.out
- test/testReferenceFiles/test_miranda_copybench.out
- test/testReferenceFiles/test_miranda_inorderstream.out
- test/testReferenceFiles/test_miranda_randomgen.out
- test/testReferenceFiles/test_miranda_revsinglestream.out
- test/testReferenceFiles/test_miranda_singlestream.out
- test/testReferenceFiles/test_miranda_stencil3dbench.out
- test/testReferenceFiles/test_miranda_streambench.out
Added new prefetch stats which changes the output for miranda & cassini
> Update reference files for sst-elements PR #417 in elements

- test/testSuites/testSuite_prospero.sh
Don't attempt prospero Pin on Yosemite.  It fails.
> No pin yosemite

- buildsys/bamboo.sh
Update (long unused) no-mpi scenario to include extras required for current tests.
> For no mpi

- test/testSuites/testSuite_scheduler.sh
Adjust test  Suite for changes going to split core
> benign errors in scheduler tests

- test/utilities/timeLimitEnforcer.sh
> Avoid timelimit Infinite loop

- test/utilities/timeLimitEnforcer.sh
Get rid of the bash syntax error.
> Prevent the infinite loop in Issue #342

- test/utilities/timeLimitEnforcer.sh
Change syntax on ps command to a form accept by Apple as well as Linux
> Change syntax on ps command

- test/testSuites/testSuite_partitioner.sh
- test/testSuites/testSuite_prospero.sh
- test/testSuites/testSuite_qsimComponent.sh
Change 3 test Suites to use variable, "RetVal", as all other Suites do.   It may help with Auto editing for Valgrind.
> Tweak consistancy

- test/testSuites/testSuite_EmberSweep.sh
Cosmetic and clarifying clean up found while trying to integrate Valgrind in the possibilities
> Minor clean up

- test/testSuites/testSuite_EmberSweep.sh
Ember Sweep accepts list of tests to run.   Allow also entries that describe multiple tests
> Add optional inclusive sublist to the EmberSweep Suite

- buildsys/bamboo.sh
Retry the clone of core and elements up to 2 more times if it fails.
> Three tries

- test/testSuites/testSuite_merlin.sh
- test/testSuites/testSuite_partitioner.sh
add suite name to the output file names on the partitioner.
Removed some noisy output from a test Suite
> Bit of cleanup

- test/testReferenceFiles/test_cassini_prefetch_nbp.out
- test/testReferenceFiles/test_cassini_prefetch_nopf.out
- test/testReferenceFiles/test_cassini_prefetch_sp.out
- test/testReferenceFiles/test_chdlComponent.out
- test/testReferenceFiles/test_miranda_copybench.out
- test/testReferenceFiles/test_miranda_inorderstream.out
- test/testReferenceFiles/test_miranda_randomgen.out
- test/testReferenceFiles/test_miranda_revsinglestream.out
- test/testReferenceFiles/test_miranda_singlestream.out
- test/testReferenceFiles/test_miranda_stencil3dbench.out
- test/testReferenceFiles/test_miranda_streambench.out
- test/testReferenceFiles/test_qsimComponent.out
Lost this code somewhere after it was checked and verified on gitHub
> Try Again at matching Mike

- test/testSuites/testSuite_memHierarchy_sdl.sh
> Very Slightly ease Match Criteron

- test/testSuites/testSuite_memHierarchy_sdl.sh
This reverts commit a8bc90cab4f75a9d75b7a64b01eeb09c506ddd7b.
> Revert "Very Slightly ease Match Criteron"

- test/utilities/timeLimitEnforcer.sh
Not pretty, but should prevent the memHierarcy Sieve testing hangs
> Clean Time limit memHS 

- buildsys/bamboo.sh
- test/testReferenceFiles/test_CramSim_1_R.out
- test/testReferenceFiles/test_CramSim_1_RW.out
- test/testReferenceFiles/test_CramSim_1_W.out
- test/testReferenceFiles/test_CramSim_2_R.out
- test/testReferenceFiles/test_CramSim_2_W.out
- test/testReferenceFiles/test_CramSim_4_R.out
- test/testReferenceFiles/test_CramSim_4_W.out
- test/testReferenceFiles/test_CramSim_5_R.out
- test/testReferenceFiles/test_CramSim_5_W.out
- test/testReferenceFiles/test_CramSim_6_R.out
- test/testReferenceFiles/test_CramSim_6_W.out
- test/testSuites/testSuite_CramSim.sh
Install CramSim Suite for nightly testing
> Cram sim tests

- test/testSuites/testSuite_CramSim.sh
Remove much noisy instrumentation.
Patch the Suite to allow the nightly to specify multi-thread.
Add more error reporting on test failure.
> Clean up CramSim test Suite

- test/utilities/timeLimitEnforcer.sh
SQE Issue #342.   The parameters to ps are adjusted for Linux/MacOS compatibilty.
In addition, comments added to the timeLimitEnforcer script.
> Try again tl mac os

- buildsys/bamboo.sh
Bamboo.sh support for "Build Only" option.
Environment variable flag is SST_STOP_AFTER_BUILD
> Jon's requested changes

- buildsys/bamboo.sh
- test/include/testDefinitions.sh
- test/testSuites/testSuite_memHA.sh
- test/testSuites/testSuite_memHierarchy_sdl.sh
Adaptation to testing to do the test without requiring the reference files be included in the Release
> For make dist

- test/testSuites/testSuite_Ariel.sh
- test/testSuites/testSuite_CramSim.sh
- test/testSuites/testSuite_EmberSweep.sh
- test/testSuites/testSuite_Samba.sh
- test/testSuites/testSuite_SiriusZodiacTrace.sh
- test/testSuites/testSuite_VaultSim.sh
- test/testSuites/testSuite_cacheTracer.sh
- test/testSuites/testSuite_cassini_prefetch.sh
- test/testSuites/testSuite_chdlComponent.sh
- test/testSuites/testSuite_embernightly.sh
- test/testSuites/testSuite_memHSieve.sh
- test/testSuites/testSuite_merlin.sh
- test/testSuites/testSuite_miranda.sh
- test/testSuites/testSuite_prospero.sh
- test/testSuites/testSuite_scheduler.sh
- test/testSuites/testSuite_simpleComponent.sh
- test/testSuites/testSuite_simpleDistribComponent.sh
- test/testSuites/testSuite_simpleLookupTableComponent.sh
- test/testSuites/testSuite_simpleMessageGeneratorComponent.sh
- test/testSuites/testSuite_simpleRNGComponent.sh
- test/testSuites/testSuite_simpleStatisticsComponent.sh
Changes to test Suites to use Reference files from Elements  (Issue #447)
> Use el ref

- buildsys/bamboo.sh
Add embernightly to the Hammer repetitive loop.   (this is the bufLen test.)
> Add Embernightly

- test/testSuites/testSuite_chdlComponent.sh
Ignore the new Warning message in CHDL test from MemHierarchy
> Chdl mem h warning

- test/testSuites/testSuite_memHA.sh
Use separate Reference files for multi-core on the memHA Suite
> Use separate Refs for MC

- test/testSuites/testSuite_hybridsim.sh
Use the HybridSim Reference file in memHierarchy/tests/refFiles.
Re-enable the HybridSim test
> Hbs use ref

- test/testSuites/testSuite_CramSim.sh
- test/testSuites/testSuite_prospero.sh
- test/utilities/invokeSuite
Small adjustments in test Suites to accommodate automatic testing of Output Config
> Small fixes for oc

- test/testSuites/testSuite_hybridsim.sh
Merge hybridSim Suite changes to branch, RNGtemplate
> Tweak hybirdSim Suite for output config test

- test/testSuites/testSuite_VaultSim.sh
- test/testSuites/testSuite_simpleRNGComponent.sh
Merge changes in support of Output Config Testing.
> RNGtemplate

- test/testSuites/testSuite_embernightly.sh
- test/testSuites/testSuite_simpleLookupTableComponent.sh
tweak embernightly for outPut ConFig test.   Still not working!
Add a peak at prior output when sst finishes abnormally (on one Suite)
> Fix 2 suites

- test/utilities/stackback.py
Adds a utility for generating stack traces.   Needs to be integrated into the timeLimitEnforcer.
> Initial implementation of a stack tracing utility

- buildsys/bamboo.sh
- test/testSuites/testSuite_simpleSimulation.sh
- test/testSuites/testSuite_simpleSimulation_CarWash.sh
Activate the Car Wash test in Suite,
testSuite_simpleSimulation_CarWash
> Car wash suite

- buildsys/bamboo.sh
- test/testSuites/testSuite_Messier.sh
Install and activate the Messier test Suite
> Do messier

- test/utilities/stackback.py
Merge Branden's change to devel
> Squelch stderr from debuggers

- test/testSuites/testSuite_Ariel.sh
List stream executables.
On Mac OS,  delete at end of Suite.
> Worry re streams

- test/testSuites/testSuite_BadPort.sh
Field the time limit even on an unconventional test.
> Process_TL

- test/include/testDefinitions.sh
- test/include/testSubroutines.sh
- test/testSuites/testSuite_Ariel.sh
- test/testSuites/testSuite_Messier.sh
- test/testSuites/testSuite_Samba.sh
- test/testSuites/testSuite_SiriusZodiacTrace.sh
- test/testSuites/testSuite_VaultSim.sh
- test/testSuites/testSuite_cacheTracer.sh
- test/testSuites/testSuite_embernightly.sh
- test/testSuites/testSuite_hybridsim.sh
- test/testSuites/testSuite_memHA.sh
- test/testSuites/testSuite_memHierarchy_sdl.sh
- test/testSuites/testSuite_merlin.sh
- test/testSuites/testSuite_partitioner.sh
- test/testSuites/testSuite_simpleComponent.sh
- test/testSuites/testSuite_simpleLookupTableComponent.sh
- test/testSuites/testSuite_simpleSimulation_CarWash.sh
- test/testSuites/testSuite_zoltan.sh
merge the code for map-by-numa on tests with mpirun
> Map by numa

- test/testSuites/testSuite_partitioner.sh
Partitioner test Suite is adherently Multi Rank.   Don't confuse things by mixing two differing requests for number of ranks.   Omit running the Suite in multi-  Projects
> Desired partitioner

- test/testSuites/testSuite_Messier.sh
- test/testSuites/testSuite_Samba.sh
- test/testSuites/testSuite_SiriusZodiacTrace.sh
- test/testSuites/testSuite_cacheTracer.sh
- test/testSuites/testSuite_memHA.sh
- test/testSuites/testSuite_memHierarchy_sdl.sh
- test/testSuites/testSuite_merlin.sh
- test/testSuites/testSuite_simpleComponent.sh
- test/testSuites/testSuite_simpleLookupTableComponent.sh
- test/testSuites/testSuite_simpleSimulation_CarWash.sh
Apparently benign, but remove duplicate parameter from 10 Suites
> Remove duplicated parameter from Suites

- buildsys/bamboo.sh
> Jpvandy run messier

- test/utilities/insertValgrind
This only matters if the Messier test is enabled in bamboo
> Add Messier Suite to Weekly Valgrind list

- test/include/testSubroutines.sh
Clean up edge case in removing left behind (by Ariel) stream executing binaries.
> Log parent pid

- test/testSuites/testSuite_CramSim.sh
- test/testSuites/testSuite_SiriusZodiacTrace.sh
- test/testSuites/testSuite_prospero.sh
Insert the no-check-certificate code in three testSuites
> No cert check

- test/utilities/timeLimitEnforcer.sh
timeLimitEnforcer:
Corrected Traceback call for mpirun case.
Insert deadlock check code in time limit processing  Issue #636
> Dlock and mpirun

- test/utilities/timeLimitEnforcer.sh
Consolidate some readability and output clarification changes in Time Limit processing
> House keeping changes

- test/testSuites/testSuite_memHSieve.sh
- test/utilities/timeLimitEnforcer.sh
move the memHSieve house cleaning from time limit enforcer to the memHSieve Suite
> Relocate ompsieve cleanup

- buildsys/bamboo.sh
Include the External Element in the make-dist test Suite
> Find External Element for testing

- buildsys/bamboo.sh
- test/testSuites/testSuite_sst_info_test.sh
> Sst info test

- test/utilities/timeLimitEnforcer.sh
time LImit Enforcer:
Use better criterion for finding sst pid.
Only do the deadlock test if multi core.
> Needed enhancements to tLE

- test/include/testSubroutines.sh
- test/testSuites/testSuite_memHSieve.sh
- test/utilities/timeLimitEnforcer.sh
Move the ompsievetest clean up from timeLimitEnforcer to memHSieve Suite
> Tl 4 mem hs

- buildsys/bamboo.sh
Add write to log of CPU count from dotests in bamboo.sh
> add cpu count

- test/utilities/timeLimitEnforcer.sh
> Remove ' sst' selection option from TL

- test/testSuites/testSuite_memHSieve.sh
- test/utilities/timeLimitEnforcer.sh
Primarily updates to the Time Limit Enforcer
> 4push2devel

- test/utilities/invokeSuite
Standardize names in invokeSuite
> Standardize names to actual counts

- test/utilities/timeLimitEnforcer.sh
Remove easy stuff from the merged time Limit Enforcer.   Relatively litter change in functionality.  Increase readability.    At this point only the first page or so is shared code between Linux and Mac.
> Clean-up pass-1

- test/utilities/timeLimitEnforcer.sh
> Mac tl patch2

- test/utilities/timeLimitEnforcer.sh
Restore some cleanup of orphan ompsievetest tasks
Cosmetic: significantly realign script through the Linux section of timeLimitEnforcer
> Much editing, litle logic change

- buildsys/bamboo.sh
- test/testSuites/testSuite_merlin.sh
Merge the SQE code to match the updated Merlin element to devel.
At this point it is expect to break the Nightly, but currently merge to Master is already turned off awaiting resolution of the Merlin issue with Multi-Rank.   This should not impact the devel Automerge because the Merlin issue was not noticed by the devel Autotester.
> For merlin

- buildsys/bamboo.sh
- test/testInputFiles/ES2_List-of-Tests
- test/testSuites/testSuite_ES2.sh
Test had two names scatter through, "newES" and "ES2".
> Rename to ES2

- test/testSuites/testSuite_ES2.sh
Adds the ability to call out which tests to run from the 126 in ES2
> The test selection code

- test/utilities/invokeSuite
> From Devel

- buildsys/bamboo.sh
- test/testSuites/testSuite_ES2.sh
- test/utilities/insertValgrind
Add an ES2,  (second EmberSweep tests) test to Automated Valgrind configuring.
> Add es2 vg

- test/testSuites/testSuite_cassini_prefetch.sh
- test/utilities/timeLimitEnforcer.sh
Tweak Prefetcher test and Linux time limit Enforcer
> Testing details

- test/testSuites/testSuite_ES2.sh
Turn on enforcement of simulation time compare in the ES2  sweep test
> Play w es2

- test/testSuites/testSuite_ES2.sh
ES2 Suite   (Ember Sweep Shmem)
Update the Reference file for recent FireFly changes.
Move Input list to ember/test from SQE/testInputFiles  (Names evolving from ES2 - ES Shmem)
> ES2 Suite changes

- test/testSuites/testSuite_memHA.sh
(thought I did this previously.)
> Add Goblin tests

- buildsys/bamboo.sh
- test/testSuites/testSuite_juno.sh
Add the juno test Suite and the bamboo.sh (dotests) invocation of same.
> Juno test Suite

- buildsys/bamboo.sh
- test/testInputFiles/ESshmem_List-of-Tests
- test/testSuites/testSuite_ESshmem.sh
- test/utilities/insertValgrind
- test/utilities/invokeSuite
Rename the ES2 test Suite as ESshmem
Hopefully clean out the various stray variations, ES2, newES, ES-shmem and ES_shmem
> Name-ESshmem

- test/testSuites/testSuite_memHA.sh
> Only use MC refFile if it exist

- test/testSuites/testSuite_memHA.sh
code was terminating Suite on a Bash err.
> Remove bailing wire patch

- test/testSuites/testSuite_embernightly.sh
remove December left overs from release older than two days
> Ember garbage

- buildsys/bamboo.sh
A additional Multi test to auto tester
> Add one new test

- test/testSuites/testSuite_memHA.sh
Add two Kingsley test to memHA
> Johns mem ha

- buildsys/bamboo.sh
allow metis selection on Ubuntu 18.04
> U18 metis b

- buildsys/bamboo.sh
> add ability to use MPI from ~/jpvandy on sst-test to bamboo

- test/testSuites/testSuite_Sweep_openMP.sh
The option ask for test #n thru #m as n-m is added to Suite_openMP_Sweep.  (the implimentation is required to be different than in EmberSweep and ESshmem.)
> Add inclusive option to list of tests to run 

- test/include/TimeLimit-Linux.sh
- test/testSuites/testSuite_ESshmem.sh
Enhance comments and instrumentation.
Clean up Time Limit processing with Valgrind
> Add ln tl linux

- test/include/testSubroutines.sh
remove extra Warning messages from MR=2
> MT on sst-test2

- test/testSuites/testSuite_shogun.sh
remove extra Warning messages from MR=2
call RemoveComponentWarning from Shogun test Suite
For Shogun test, do a sorted compare if needed
> Changes to accomodate shogun Multi- tests

- test/testSuites/testSuite_shogun.sh
> missing line

- test/testSuites/testSuite_juno.sh
Temporary fix for PMIX error messages
> PMIX error removal

- test/testSuites/testSuite_partitioner.sh
Make zoltan tests use a logical OR
> Make zoltan tests use a logical OR

- test/testSuites/testSuite_sst_GNA.sh
This reverts commit 3ea25a61a1f21dc35acf64a33829645ff42c142f, reversing
changes made to cf748e792c7963bbc064bcc08b1d2bce68ada578.
> Revert "Merge pull request #978 from sstsimulator/my-GNA"

- buildsys/bamboo.sh
- test/testSuites/testSuite_simpleComponent.sh
Changes to have Scott's sub component tests pass SQE Make Dist tests
> With legacy

- buildsys/bamboo.sh
- buildsys/deps/bin/sstDep_GPGPUSim.sh
- test/testSuites/testSuite_gpgpu.sh
Updating paths to reflect renaming GPU component.
> Balar Addition

- buildsys/bamboo.sh
Fixed Balar repo
Fixed splitting of GPGPU-Sim and Balar
> Balar Fixes

- buildsys/bamboo.sh
Creat path to invoke a test Suite in dotests of Bamboo.sh
> ADD run Suites option

- test/testSuites/testSuite_EmberSweep.sh
> increase time limit

- buildsys/bamboo.sh
- test/testInputFiles/EmberSweepGenerator.py
- test/testSuites/testSuite_EmberSweep.sh
These changes should be transparent to existing Py2 Testing
> Add Python3 support

- test/testSuites/testSuite_simpleComponent.sh
Fix for multirank on simpleComponent; missed setting errFile in a couple of places
> Fix for multirank on simpleComponent; missed setting errFile

- buildsys/bamboo.sh
- test/testSuites/testSuite_memHA.sh
Plus a minor correction to bamboo
> Cleanup testSuite_memHA.sh

- buildsys/bamboo.sh
> Fixes for OSX 10.15

- buildsys/bamboo.sh
Change to have Bamboo choose PY3 by default (if possible) - ie make PY3 the priority.
> Changes to make detection of Py3 the priority

- buildsys/bamboo.sh
Revamped the algorithm to find priority detect Python3 to play nicer with the osx 10.15 goofiness
> Revamped the algorithm to find priority detect Python3 to play nice

- buildsys/bamboo.sh
- buildsys/deps/bin/sstDep_GPGPUSim.sh
- buildsys/deps/bin/sstDependencies.sh
- test/testSuites/testSuite_gpgpu.sh
Moving balar build and test to the devel branch
> Moving balar build and test

- buildsys/bamboo.sh
Zoltan is being removed from core via Core PR num 631
> Removing zoltan build and test from bamboo

- buildsys/bamboo.sh
"Removing zoltan build and test from bamboo per removal from core via PR #631"
This reverts commit 6ddc6b80b56d449237ea0111030c100f3feaf3a7.
> Revert "Removing zoltan build and test from bamboo"

- README.md
I recently learned this on 2021-12-15
> explanation of tests for SST

- LICENSE
from https://github.com/sstsimulator/sst-documentation/blob/main/LICENSE
> copy from sst-documentation

- buildsys/bamboo.sh
- buildsys/deps/include/depsDefinitions.sh
- test/include/TimeLimit-Linux.sh
- test/include/TimeLimit-MacOS.sh
- test/include/testDefinitions.sh
- test/include/testSubroutines.sh
- test/utilities/moduleex.sh
We can tidy and fix some obvious problems before deciding what to do with bamboo.  Closes #7.
> Spring cleaning

- buildsys/bamboo.sh
> Spring cleaning part 2

- buildsys/bamboo.sh
- buildsys/deps/include/depsDefinitions.sh
- test/include/TimeLimit-Linux.sh
- test/include/TimeLimit-MacOS.sh
- test/include/testDefinitions.sh
- test/include/testSubroutines.sh
- test/testSuites/testSuite_macro.sh
- test/utilities/moduleex.sh
A follow-up to #1094 and #1095.  `testSuite_macro` is stil failing, I think in the subshell used for `make`.
> Spring cleaning take 3

- buildsys/bamboo.sh
> Don't make clean for macro

- buildsys/bamboo.sh
> Missing popd after make dist on elements

- buildsys/bamboo.sh
> Set `SST_*_HASH` via indirection rather than echo returns

- buildsys/bamboo.sh
- buildsys/deps/bin/sstDep_hybridsim.sh
- buildsys/deps/bin/sstDependencies.sh
- buildsys/deps/patches/HybridSim.patch
- buildsys/deps/patches/NVDIMMSim.patch
- buildsys/deps/patches/ramulator_include.patch
- test/utilities/moduleex.sh
These fixes were required to get builds working on Rocky 9 and Ubuntu 24.04.
> Fixes for modules and compilation with GCC 13.2.0

- buildsys/bamboo.sh
- test/utilities/moduleex.sh
> Update lmod error detection

- .github/workflows/test.yml
- buildsys/bamboo.sh
Reverts sstsimulator/sst-sqe#1123
Problems with `module load ...` on some machines.  Need https://github.com/sstsimulator/sst-sqe/issues/1157.
> Revert "Support Clang on Linux"

- buildsys/bamboo.sh
- buildsys/deps/bin/sstDependencies.sh
- buildsys/deps/patches/dramsim3_cmake_version.patch
Closes https://github.com/sstsimulator/sst-sqe/issues/1163
> Patch DRAMSim3 for newer CMake versions

- .github/workflows/test.yml
Undo part of https://github.com/sstsimulator/sst-sqe/pull/1162
> CI: unpin core

- .github/scripts/install_os_level_dependencies.sh
- .github/workflows/test.yml
> GitHub Actions: switch build matrix to inclusion

- .github/scripts/call_bamboo.sh
- .github/scripts/install_os_level_dependencies.sh
- .github/workflows/test.yml
Contains some of the work for #1157 and #1158.
> CI: set up environment modules and install Spack
